name: Lint code base

on:
  pull_request:
    branches: [ trunk ]

jobs:
  lint-pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
      - name: Install requirements
          working-directory: ai/src
          run: |
            pip install -r requirements.txt
      - name: Install pylint
          working-directory: ai/src
          run: |
            pip install pylint
      - name: Analysing the AI code with pylint
          working-directory: ai/src
          run: |
            pylint spicepy

  lint-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
      - name: Install requirements
          working-directory: ai/src
          run: |
            pip install -r requirements.txt
      - name: Install flake8
          working-directory: ai/src
          run: |
            pip install flake8
      - name: Analysing the AI code with flake8
          working-directory: ai/src
          run: |
            flake8 spicepy