name: Test code base

on:
  pull_request:
    branches:
      - trunk
  push:
    branches:
      - trunk
      - release-*
    tags:
      - v*

jobs:
  test_pip_install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: Test with pip install ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pip install
        run: |
          pip install .

  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: Test on ${{ matrix.os }} with pytest ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install requirements
        run: |
          pip install ".[test]"

      - name: install Spice
        if: matrix.os != 'windows-latest'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          function curl() {
            if [ -z "$GH_TOKEN" ]
            then
              command curl -H "Accept: application/vnd.github.v3.raw" \
                $@
            else
              command curl -H "Accept: application/vnd.github.v3.raw" \
                -H "Authorization: token $GH_TOKEN" \
                $@
            fi
          }
          curl https://install.spiceai.org | /bin/bash
          echo "$HOME/.spice/bin" >> $GITHUB_PATH

      - name: install Spice (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          curl -L "https://install.spiceai.org/Install.ps1" -o Install.ps1 && PowerShell -ExecutionPolicy Bypass -File ./Install.ps1

      - name: add Spice bin to PATH (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Add-Content $env:GITHUB_PATH (Join-Path $HOME ".spice\bin")
        shell: pwsh

      - name: Init and start spice app
        if: matrix.os != 'windows-latest'
        run: |
          spice init spice_qs
          cd spice_qs
          spice add spiceai/quickstart
          spice run &> spice.log &
          # time to initialize added dataset
          sleep 10

      - name: Init and start spice app (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          spice init spice_qs
          cd spice_qs
          spice add spiceai/quickstart
          Start-Process -FilePath spice run
        shell: pwsh

      - name: Running tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          pytest -s
