name: Create Tag and Draft Release with Notes

on:
  push:
    branches:
      - trunk
    paths:
      - 'setup.py'
  workflow_dispatch:

jobs:
  check-and-extract:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      tag-exists: ${{ steps.check-tag.outputs.exists }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Extract version from setup.py
        id: get-version
        run: |
          VERSION=$(cat setup.py | grep -E '^ +version="[0-9.]+",' | cut -d'"' -f2)
          echo "Extracted version is $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          
      - name: Check if tag exists
        id: check-tag
        run: |
          if git tag | grep -q "${{ steps.get-version.outputs.version }}"; then
            echo "Tag exists"
            echo "exists=1" >> "$GITHUB_OUTPUT"
          else
            echo "Tag does not exist"
            echo "exists=0" >> "$GITHUB_OUTPUT"
          fi

  create-tag-and-release:
    needs: check-and-extract
    if: needs.check-and-extract.outputs.tag-exists == '0'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create and push tag
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git tag ${{ needs.check-and-extract.outputs.version }}
          git push origin ${{ needs.check-and-extract.outputs.version }}

      - name: Install GitHub CLI
        run: |
          sudo apt update && sudo apt install -y curl gpg
          sudo curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg;
          sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null;
          sudo apt update && apt install -y gh;

      - name: Draft a new release with autogenerated notes
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create ${{ needs.check-and-extract.outputs.version }} --title "Release ${{ needs.check-and-extract.outputs.version }}" --generate-notes --draft
